#!/bin/bash -e
# (-ex is verbose)
##############################################################################################################
##############################################################################################################
###                                                                                                        ###
###  Please customize the following VARIABLEs:                                                             ###
###                                             SOC=                                                       ###
###                                             CUSTOM_DTS_NAME=                                           ###
###						SOURCES_BASE_PATH=                                         ###
###                                             SDK_BUILD_ENV_BASE=                                        ###
###                                                                                                        ###
##############################################################################################################
##############################################################################################################

#####################################################
###                                          ########
###    OPTIONAL CUSTOM CONFIGURATION         ########
###                                          ########
#####################################################

#################################################################
### CUSTOM EXTERNAL DEVICETREE                                ###
### If EXTDT_WORKING_DIR is defined, EXTDT_DIR will be ignored ###
###                                                           ###
EXTDT_WORKING_DIR="STM32MPU-OSTL-DEV-helper/DEVICETREE/CUSTOM_EXT_DTS_FOR_STM32MP135F-DK"
# EXTDT_WORKING_DIR="STM32MPU-OSTL-DEV-helper/DEVICETREE/CUSTOM_EXT_DTS_FOR_STM32MP157F-DK2"
### 
### DEVICETREE FOLDER generated by CubeMX:                    ###
# USE_CUBEMX_PRJ_DIR="STM32MPU-OSTL-DEV-helper/DEVICETREE/STM32MP25x_CubeMX/CA35/DeviceTree/"
###                                                           ###
### CubeMX Project name:                                      ###
# CUBEMX_PRJ_NAME="dk-v6.1" # <- This definition overrides CUSTOM_DTS_NAME value!!
##
#################################################################

###########################################################################
# Build FIP and TF-A for this BOOT_DEVICE 
# available BOOT_DEVICE: "emmc" "sdcard" "nor"
BOOT_DEVICE="sdcard"
DRAM_SIZE="0x20000000"

###########################################################################
# OPTEE version: standard or min
# Available options: "optee" - "opteemin"
# OPTEE_TYPE="opteemin"
OPTEE_TYPE="optee"

###########################################################################
# Programming channel
# Available options: "usb" - "uart"
PRG_BUS="usb"

### CUSTOM u-boot configs file ######################
# CUSTOM_UBOOT_DEFCONFIG="STM32MPU-OSTL-DEV-helper/STM32MPU-OSTL-DEV-helper/TEMPLATES/STM32MP1/CONFIGS/stm32mp13_defconfig_u-boot"
# CUSTOM_UBOOT_DEFCONFIG="STM32MPU-OSTL-DEV-helper/STM32MPU-OSTL-DEV-helper/TEMPLATES/STM32MP1/CONFIGS/stm32mp15_defconfig_u-boot"

##############################################################################################################
###                                                                                                 ##########
###          MANDATORY DEFINITIONs                                                                  ##########
###                                                                                                 ##########
##############################################################################################################

STM32MP_PLATFORM="stm32mp1"

# MP15
# SOC_BASE="stm32mp15"
# SOC="${SOC_BASE}7c"

# MP13
SOC_BASE="stm32mp13"
SOC="${SOC_BASE}5f"

### DTS name (external dts, can be a custom name) ###
## ST board DTS names
# CUSTOM_DTS_NAME="${SOC}-ev1"
# CUSTOM_DTS_NAME="${SOC}-dk2"
# CUSTOM_DTS_NAME="${SOC}-dk"

CUSTOM_DTS_NAME="${SOC}-myboard"

SOURCES_BASE_PATH="./"
SDK_BUILD_ENV_BASE="/opt/st/${STM32MP_PLATFORM}/5.0.8-openstlinux-6.6-yocto-scarthgap-mpu-v25.06.11"

##############################################################################################################
###                                                                                                 ##########
###          OPTIONAL SETTINGs                                                                      ##########
###                                                                                                 ##########
##############################################################################################################

BUILD_TFA="1"    # Build tfa + FIP
BUILD_OPTEE="1"  # Build optee + FIP
BUILD_UBOOT="1"  # Build uboot + FIP

DO_CLEAN="1"     # Clean up the build folder & FIP_artifacts folder before build.
DO_CLEAN_DTB="1" # Clean up all DTBs before build.
DO_CLEAN_ALL="1" # Clean up FIP_artifacts folder.

BUILD_HELPER_OUTPUT="1" # Copy final artifact in OUT folder and create tar.gz archive (under ./BUILD_OUTPUT) 

##############################################################################################################
###                                                                                                 ##########
###          SYSTEM ENVIRONMENT                                                                     ##########
###                                                                                                 ##########
##############################################################################################################

SDK_BUILD_ENV_PATH="${SDK_BUILD_ENV_BASE}/environment-setup-cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi"

for component in optee-os tf-a u-boot; do
    [[ "x`ls -1d ${component}-stm32mp-*-stm32mp*-r*-r* 2>/dev/null`" == "x" ]] && continue

       component_ver=`ls -1d ${component}-stm32mp-*-stm32mp*-r*-r* | sed -e "s/${component}-stm32mp-\(.*\)-stm32mp-r\(.*\)-r\(.*\)/\1/g"`
    component_ver_Ra=`ls -1d ${component}-stm32mp-*-stm32mp*-r*-r* | sed -e "s/${component}-stm32mp-\(.*\)-stm32mp-r\(.*\)-r\(.*\)/\2/g"`
    component_ver_Rb=`ls -1d ${component}-stm32mp-*-stm32mp*-r*-r* | sed -e "s/${component}-stm32mp-\(.*\)-stm32mp-r\(.*\)-r\(.*\)/\3/g"`

    case ${component} in
	"tf-a")
	  	tfa_ver_Rb=${component_ver_Rb}
		TFA_DIR="${component}-stm32mp-${component_ver}-stm32mp-r${component_ver_Ra}-r${component_ver_Rb}/${component}-stm32mp-${component_ver}-stm32mp-r${component_ver_Ra}"
		;;
	"optee-os")
	  	optee_ver_Rb=${component_ver_Rb}
		OPTEE_DIR="${component}-stm32mp-${component_ver}-stm32mp-r${component_ver_Ra}-r${component_ver_Rb}/${component}-stm32mp-${component_ver}-stm32mp-r${component_ver_Ra}"
		;;
	"u-boot")
	  	uboot_ver_Rb=${component_ver_Rb}
		UBOOT_DIR="${component}-stm32mp-${component_ver}-stm32mp-r${component_ver_Ra}-r${component_ver_Rb}/${component}-stm32mp-${component_ver}-stm32mp-r${component_ver_Ra}"
		;;
    esac
done

NUM_COREs=4

cd ${SOURCES_BASE_PATH}
CURDIR=`pwd`

if [ -z "${EXTDT_WORKING_DIR}" ]; then
   EXTDT_DIR="${CURDIR}/${EXTERNAL_DT_DIR}"
 else
   for d in tf-a optee u-boot; do
     [[ ! -d "${EXTDT_WORKING_DIR}/${d}" ]] && echo -e "\n\tError: folder ${EXTDT_WORKING_DIR}/${d} does not exist, please correct the path\n\n" && exit 0
   done
   EXTDT_DIR="${CURDIR}/${EXTDT_WORKING_DIR}"
fi

SDK_HELPER_OUTPUT="BUILD_OUTPUT"
SDK_HELPER_OUTPUT_FIP="${SDK_HELPER_OUTPUT}/fip"
SDK_HELPER_OUTPUT_TFA="${SDK_HELPER_OUTPUT}/tfa"

FIP_DEPLOYDIR_ROOT="${CURDIR}/FIP_artifacts"

##############################################################################################################
##############################################################################################################
###                                                                                                 ##########
###          START OF OPERATIONs                                                                    ##########
###                                                                                                 ##########
##############################################################################################################
##############################################################################################################

if [[ "x${DO_CLEAN_ALL}" = "x1" ]]; then
  DO_CLEAN="1"
  rm -rf ${FIP_DEPLOYDIR_ROOT}
fi

FIP_CONFIGs="${OPTEE_TYPE}-${BOOT_DEVICE} ${OPTEE_TYPE}-programmer-${PRG_BUS}"

# Toolchain setup
source ${SDK_BUILD_ENV_PATH}
export EXTDT_DIR

function do_manage_cubemx_prj() {
  if [[ ! -d "${CUBEMX_PRJ_DIR}" ]]; then
     echo ""
     echo " Missing or unaccessible CubeMX project folder: ->${CUBEMX_PRJ_DIR}<- !"
     echo " Exiting now."
     echo ""
     exit 0
  fi
  if [[ -z "${EXTDT_WORKING_DIR}" ]]; then
     echo ""
     echo " Missing External DTS folder definition: ->${EXTDT_WORKING_DIR}<- !"
     echo " Exiting now."
     echo ""
     exit 0
  fi

  # Adjust misaligned paths
  cd ${EXTDT_WORKING_DIR}/
  mkdir -p linux optee tf-a u-boot
  [[ ! -e kernel ]] && ln -s linux kernel
  [[ ! -e optee-os ]] && ln -s optee optee-os
  cd -
  for folder in kernel optee-os tf-a u-boot; do
     cd ${EXTDT_WORKING_DIR}/${folder}
     for dtsfile in `ls ${CUBEMX_PRJ_DIR}/${folder}/*.dts ${CUBEMX_PRJ_DIR}/${folder}/*.dtsi`; do
      #  echo ${dtsfile}
       DTSNAME=`basename ${dtsfile}`
       [[ -L ${DTSNAME} ]] && rm ${DTSNAME}
       [[ -f ${DTSNAME} ]] && mv ${DTSNAME} ${DTSNAME}_BCK-`date +%Y%m%d%H%M%S`
       ln -s ${dtsfile} .
     done
     cd - > /dev/null
  done
  TEMPLATE_DIR="STM32MPU-OSTL-DEV-helper/TEMPLATES/STM32MP1"
  for folder in kernel optee-os u-boot; do
     for dtsfile in `ls ${CUBEMX_PRJ_DIR}/${folder}/*.dts`; do
       # DTSNAME=`basename ${dtsfile} | sed -e 's/\.dts$//g'`
       MKFILE="Makefile"
       [[ "${folder}" == "optee-os" ]] && MKFILE="conf.mk"
       sed -e "s/SDKHELPERTEMPLATE/${CUSTOM_DTS_NAME}/g" ${TEMPLATE_DIR}/${folder}/${MKFILE} > ${EXTDT_WORKING_DIR}/${folder}/${MKFILE}
     done
  done

}

function do_build_uboot() {

  rm -rf   ${FIP_DEPLOYDIR_ROOT}/u-boot ${FIP_DEPLOYDIR_ROOT}/fip-${CUSTOM_DTS_NAME}-*.bin
  mkdir -p ${FIP_DEPLOYDIR_ROOT}/u-boot
  
  cd ${UBOOT_DIR}

  UBOOT_DEFCONFIG="${SOC_BASE}_defconfig"
  if [ ! -z "${CUSTOM_UBOOT_DEFCONFIG}" ]; then
     if [ -f "../../${CUSTOM_UBOOT_DEFCONFIG}" ]; then
        cp -v ../../${CUSTOM_UBOOT_DEFCONFIG} configs/${SOC_BASE}_custom_defconfig
        UBOOT_DEFCONFIG="${SOC_BASE}_custom_defconfig"
     fi
  fi
  
  [[     "x${DO_CLEAN}" = "x1" ]] && make -f ../Makefile.sdk.${STM32MP_PLATFORM} UBOOT_DEFCONFIG=${UBOOT_DEFCONFIG} DEPLOYDIR=${FIP_DEPLOYDIR_ROOT}/u-boot clean
  [[     "x${DO_CLEAN}" = "x1" ]] && rm -rf ../deploy
  [[ "x${DO_CLEAN_DTB}" = "x1" ]] && rm -f ../build/${UBOOT_DEFCONFIG}/arch/arm/dts/.${SOC_BASE}* \
					   ../build/${UBOOT_DEFCONFIG}/arch/arm/dts/*dtb \
					   ${EXTDT_DIR}/u-boot/*dtb ${EXTDT_DIR}/u-boot/.${SOC_BASE}*
  [[ "x${DO_NOT_BUILD}" = "x1" ]] && cd - && return 0
  
  for dt in ${CUSTOM_DTS_NAME}; do
     make -f ../Makefile.sdk.${STM32MP_PLATFORM} DEVICE_TREE=${dt} UBOOT_CONFIG=default UBOOT_DEFCONFIG=${UBOOT_DEFCONFIG} UBOOT_DEVICETREE_EXTERNAL=${dt} \
			     			 DEPLOYDIR=${FIP_DEPLOYDIR_ROOT}/u-boot uboot
  done

  cd -
}

function do_build_optee() {
  
  rm -rf   ${FIP_DEPLOYDIR_ROOT}/optee ${FIP_DEPLOYDIR_ROOT}/fip-${CUSTOM_DTS_NAME}-*.bin
  mkdir -p ${FIP_DEPLOYDIR_ROOT}/optee

  cd ${OPTEE_DIR}

  [[ "x${DO_CLEAN}" = "x1" ]] && make -f ../Makefile.sdk.${STM32MP_PLATFORM} CFG_EMBED_DTB_SOURCE_FILE=${CUSTOM_DTS_NAME} DEPLOYDIR=${FIP_DEPLOYDIR_ROOT}/optee clean
  [[ "x${DO_CLEAN_DTB}" = "x1" ]] && rm -f ../build/${CUSTOM_DTS_NAME}/core/arch/arm/dts/.${STM32MP_PLATFORM}* out/arm-plat-${STM32MP_PLATFORM}/core/arch/arm/dts/${STM32MP_PLATFORM}*
  [[ "x${DO_NOT_BUILD}" = "x1" ]] && cd - && return 0

  OPTEE_EXTRA_OEMAKE_OPTs="-j${NUM_COREs} PLATFORM=${STM32MP_PLATFORM} CROSS_COMPILE_core=arm-ostl-linux-gnueabi- \
			  		  CROSS_COMPILE_ta_arm64=arm-ostl-linux-gnueabi- CFG_ARM32_core=y \
					  CFG_STM32MP_PROFILE=system_services CROSS_COMPILE_ta_arm32=arm-ostl-linux-gnueabi- \
					  ARCH=arm NOWERROR=1 CFG_DRAM_SIZE=${DRAM_SIZE}\
			  		  CFG_EXT_DTS=${EXTDT_DIR}/optee LDFLAGS= CFG_TEE_CORE_LOG_LEVEL=2 \
			  		  CFG_TEE_CORE_DEBUG=n CFG_${SOC_BASE}=y"
 
  make -f ../Makefile.sdk.${STM32MP_PLATFORM} CFG_EMBED_DTB_SOURCE_FILE=${CUSTOM_DTS_NAME} DEPLOYDIR=${FIP_DEPLOYDIR_ROOT}/optee OPTEE_CONFIG=${OPTEE_TYPE} EXTRA_OEMAKE="${OPTEE_EXTRA_OEMAKE_OPTs}" optee

  cd -
}

function do_build_tfa() {
  
  rm -rf   ${FIP_DEPLOYDIR_ROOT}/arm-trusted-firmware ${FIP_DEPLOYDIR_ROOT}/fip-${CUSTOM_DTS_NAME}-*.bin

  cd ${TFA_DIR}
 
  TFA_COMMON_OPTs="ELF_DEBUG_ENABLE=1 DEPLOYDIR=${FIP_DEPLOYDIR_ROOT}/arm-trusted-firmware"
  TFA_EXTRA_OEMAKE_OPTs="-j${NUM_COREs} PLAT=${STM32MP_PLATFORM} ARCH=aarch32 ARM_ARCH_MAJOR=7 CROSS_COMPILE=arm-ostl-linux-gnueabi- \
					DEBUG=0 LOG_LEVEL=40 AARCH32_SP=optee \
					TFA_EXTERNAL_DT=${EXTDT_DIR}/tf-a"

  for tfa_target in ${FIP_CONFIGs}; do
   
     if [[ "x${tfa_target}" == "xusb" ]]; then
        TGT_OPTs="STM32MP_USB_PROGRAMMER=1"
     elif [[ "x${tfa_target}" == "xsdcard" ]]; then
        TGT_OPTs="PSA_FWU_SUPPORT=1 STM32MP_SDMMC=1"
     elif [[ "x${tfa_target}" == "xemmc" ]]; then
        TGT_OPTs="PSA_FWU_SUPPORT=1 STM32MP_EMMC=1"
     fi
     TFA_SPECIFIC_OPTs="TF_A_CONFIG=${tfa_target} TF_A_DEVICETREE=${CUSTOM_DTS_NAME} ${TGT_OPTs}"
     
     [[ "x${DO_CLEAN}" = "x1" ]] && make -f ../Makefile.sdk.${STM32MP_PLATFORM} ${TFA_SPECIFIC_OPTs} clean
     [[ "x${DO_CLEAN_DTB}" = "x1" ]] && rm -fr ../build/${tfa_target}${CUSTOM_DTS_NAME}/fdts
       
     # Build stm32 binary (foreach TF_A_CONFIG)
     make -f ../Makefile.sdk.${STM32MP_PLATFORM} ${TFA_COMMON_OPTs} ${TFA_SPECIFIC_OPTs} EXTRA_OEMAKE="${TFA_EXTRA_OEMAKE_OPTs}" stm32
  done
  
  make -f ../Makefile.sdk.${STM32MP_PLATFORM} DEPLOYDIR=${FIP_DEPLOYDIR_ROOT}/arm-trusted-firmware metadata

  cd -
}


function do_build_fip() {
  
  cd ${UBOOT_DIR}
  
  for storage in ${BOOT_DEVICE}; do
    device="${OPTEE_TYPE}-${storage}"

     make -f ../Makefile.sdk.${STM32MP_PLATFORM} UBOOT_CONFIG=${device} FIP_CONFIG=${device} UBOOT_BINARY=u-boot.dtb \
			     			 FIP_DEPLOYDIR_ROOT=${FIP_DEPLOYDIR_ROOT} DEVICE_TREE=${CUSTOM_DTS_NAME} \
			     			 UBOOT_DEFCONFIG=${UBOOT_DEFCONFIG} fip
  done  

  cd -
}

[[ ! -z "${USE_CUBEMX_PRJ_DIR}" ]] && do_manage_cubemx_prj
touch /tmp/FIP_SCRIPT_done.txt
[[ "x${BUILD_UBOOT}" == "x1" ]] && do_build_uboot
[[ "x${BUILD_OPTEE}" == "x1" ]] && do_build_optee
[[   "x${BUILD_TFA}" == "x1" ]] && do_build_tfa 

mkdir -p ${FIP_DEPLOYDIR_ROOT}/fip/

do_build_fip # Assemble FIP file

echo; echo; echo

[[ "x${BUILD_HELPER_OUTPUT}" != "x1" ]] && exit 0

mkdir -p ${SDK_HELPER_OUTPUT_FIP}
mkdir -p ${SDK_HELPER_OUTPUT_TFA}

cp -v ${FIP_DEPLOYDIR_ROOT}/arm-trusted-firmware/metadata.bin 	 ${SDK_HELPER_OUTPUT_TFA}/metadata.bin

SRC_FILENAME="${CUSTOM_DTS_NAME}-${OPTEE_TYPE}-${BOOT_DEVICE}"
DST_FILENAME="${BOOT_DEVICE}"

cp -v ${FIP_DEPLOYDIR_ROOT}/arm-trusted-firmware/tf-a-${SRC_FILENAME}.stm32 \
      ${SDK_HELPER_OUTPUT_TFA}/tfa_${DST_FILENAME}.stm32
cp -v ${FIP_DEPLOYDIR_ROOT}/fip/fip-${SRC_FILENAME}.bin     ${SDK_HELPER_OUTPUT_FIP}/fip.bin

PRG_SRC_FILENAME="${CUSTOM_DTS_NAME}-${OPTEE_TYPE}-programmer-${PRG_BUS}"
PRG_DST_FILENAME="${PRG_BUS}"

cp -v ${FIP_DEPLOYDIR_ROOT}/arm-trusted-firmware/tf-a-${PRG_SRC_FILENAME}.stm32 \
      ${SDK_HELPER_OUTPUT_TFA}/tfa_${PRG_DST_FILENAME}.stm32
cp -v ${FIP_DEPLOYDIR_ROOT}/fip/fip-${SRC_FILENAME}.bin ${SDK_HELPER_OUTPUT_FIP}/fip_${PRG_DST_FILENAME}.bin

mkdir -p ${SDK_HELPER_OUTPUT}/FLASH_LAYOUT/
cp -rv STM32MPU-OSTL-DEV-helper/FLASH_LAYOUT/${STM32MP_PLATFORM}/*   ${SDK_HELPER_OUTPUT}/FLASH_LAYOUT/
mv ${SDK_HELPER_OUTPUT}/FLASH_LAYOUT/flash.sh  ${SDK_HELPER_OUTPUT}/
chmod 755 ${SDK_HELPER_OUTPUT}/flash.sh
mv ${SDK_HELPER_OUTPUT}/FLASH_LAYOUT/flash.bat ${SDK_HELPER_OUTPUT}/


tar czf /tmp/${CUSTOM_DTS_NAME}_binaries.tar.gz  ${SDK_HELPER_OUTPUT}
echo; echo
ls -lh /tmp/${CUSTOM_DTS_NAME}_binaries.tar.gz 

echo; echo; echo
exit 0
